# Generated by Django 3.1.4 on 2021-01-15 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_classification', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
